blank_issues_enabled: true
contact_links:
  - name: ðŸ“„Docs
    url: https://docs.ultralytics.com/
    about: Full Ultralytics YOLOv8 Documentation
  - name: ðŸ’¬ Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: Stack Overflow
    url: https://stackoverflow.com/search?q=YOLOv8
    about: Ask on Stack Overflow with 'YOLOv8' tag
