# Ultralytics YOLO ğŸš€, AGPL-3.0 license

blank_issues_enabled: true
contact_links:
  - name: ğŸ“„ Docs
    url: https://docs.ultralytics.com/
    about: Full Ultralytics YOLO Documentation
  - name: ğŸ’¬ Forum
    url: https://community.ultralytics.com/
    about: Ask on Ultralytics Community Forum
  - name: ğŸ§ Discord
    url: https://ultralytics.com/discord
    about: Ask on Ultralytics Discord
  - name: âŒ¨ï¸ Reddit
    url: https://reddit.com/r/ultralytics
    about: Ask on Ultralytics Subreddit
