name: Welcome WorkFlow

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  build:
    name: ğŸ‘‹ Welcome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello there, thank you for opening an Issue ! ğŸ™ğŸ» The team was notified and they will get back to you asap."
          pr-message:  "Hello there, thank you for opening an PR ! ğŸ™ğŸ» The team was notified and they will get back to you asap."
