# Basic Ultralytics validation config
# Provide weights via --weights or set `model` here.
# model: runs/detect/train/weights/best.pt

data: coco.yaml
split: val
imgsz: 640
batch: 16
device: mps
iou: 0.7
# conf: 0.25
save_json: False
name: deneme
plots: True
max_det: 300